-- Create the test table
CREATE TABLE test_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE test_items ENABLE ROW LEVEL SECURITY;

-- Create policies to allow anonymous operations
-- This allows anyone to read data
CREATE POLICY "Enable anonymous reads" 
ON test_items 
FOR SELECT 
TO anon 
USING (true);

-- This allows anyone to insert data
CREATE POLICY "Enable anonymous inserts" 
ON test_items 
FOR INSERT 
TO anon 
WITH CHECK (true);

-- Insert some sample data
INSERT INTO test_items (name, description)
VALUES 
  ('Sample Item 1', 'First sample item added via SQL'),
  ('Sample Item 2', 'Second sample item for testing');

-- Output confirmation
SELECT 'Test table created successfully with sample data' as message; 